# Use an official Python base image
FROM continuumio/miniconda3

# Set working directory
WORKDIR /app

# Copy Conda environment file to the container
COPY occenv311.yml /app/occenv311.yml
COPY stepReader.py /app/stepReader.py
COPY main.py /app/main.py
COPY dxfReader.py /app/dxfReader.py
COPY svgReader2.py /app/svgReader2.py

# Create Conda environment and activate it
RUN conda env create -f occenv311.yml
RUN conda clean -afy
RUN conda install -c conda-forge pythonocc-core=7.8.1
RUN pip install ezdxf fonttools numpy-stl python-utils typing-extensions


# Activate the Conda environment
SHELL ["conda", "run", "-n", "occenv311", "/bin/bash", "-c"]

# Set the default command
CMD ["python", "main.py"]
